// Deploy an instance of an already declared contract.
// use of OZ deployer
// launch with npx ts-node src/scripts/4.deployContractOZ.ts

import { Provider, Account, Contract, ec, json } from "starknet";
import fs from "fs";
import * as dotenv from "dotenv";
dotenv.config();


//          ðŸ‘‡ðŸ‘‡ðŸ‘‡
// ðŸš¨ðŸš¨ðŸš¨   Launch 'starknet-devnet --seed 0' before using this script.
//          Launch also the script for declaration of Test contract : script 9.
//          ðŸ‘†ðŸ‘†ðŸ‘†
async function main() {
    //initialize Provider with DEVNET, reading .env file
    if (process.env.STARKNET_PROVIDER_BASE_URL != "http://127.0.0.1:5050") {
        console.log("This script work only on local devnet.");
        process.exit(1);
    }
    const provider = new Provider({ sequencer: { baseUrl: process.env.STARKNET_PROVIDER_BASE_URL } });

    console.log('STARKNET_PROVIDER_BASE_URL=', process.env.STARKNET_PROVIDER_BASE_URL);

    // connect existing predeployed account 0 of Devnet
    console.log('OZ_ACCOUNT0_ADDRESS=', process.env.OZ_ACCOUNT_ADDRESS);
    console.log('OZ_ACCOUNT0_PRIVATE_KEY=', process.env.OZ_ACCOUNT_PRIVATE_KEY);
    const privateKey0 = process.env.OZ_ACCOUNT_PRIVATE_KEY ?? "";
    const starkKeyPair0 = ec.getKeyPair(privateKey0);
    const account0Address: string = process.env.OZ_ACCOUNT_ADDRESS ?? "";
    const account0 = new Account(provider, account0Address, starkKeyPair0);
    console.log('existing OZ account0 connected.\n');

    // Deploy Test instance in devnet
    const testClassHash = "0xff0378becffa6ad51c67ac968948dbbd110b8a8550397cf17866afebc6c17d";
    const compiledTest = json.parse(fs.readFileSync("./compiledContracts/test.json").toString("ascii"));
    const deployResponse = await account0.deployContract({ classHash: testClassHash });

    // Connect the new contract :
    const myTestContract = new Contract(compiledTest.abi, deployResponse.contract_address, provider);
    console.log('âœ… Test Contract connected at =', myTestContract.address);

}
main()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error(error);
        process.exit(1);
    });